# -*- coding: utf-8 -*-
"""cost function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1inefhU_VF9yfdZpgY6xfbai_VUJrHcTK
"""

import pandas as pd

url = "https://raw.githubusercontent.com/GrandmaCan/ML/main/Resgression/Salary_Data.csv"

data = pd.read_csv(url)
data
# y = w*x + b
x = data["YearsExperience"]
y = data["Salary"]

w = 10
b = 0
y_pred = w*x +b
cost = (y-y_pred)**2
cost.sum() / len(x)

def compute_cost(x, y ,w ,b):
   y_pred = w*x +b
   cost = (y-y_pred)**2 #cost 為(真實值-預測值)**2
   cost = cost.sum() / len(x)

   return cost

compute_cost(x, y, 8, 34)

# b = 0 w = -100~100 cost會是多少
costs=[]
for w in range(-100 ,101):
  cost = compute_cost(x, y, w, 0)
  costs.append(cost)
costs

import matplotlib.pyplot as plt
#plt.scatter(range(-100 ,101) ,costs)
plt.plot(range(-100 ,101) ,costs)
plt.title("cost function b=0 w=-100~100")
plt.xlabel("w")
plt.ylabel("cost")
plt.show()

# w = -100~100 b=-100~100 的cost
import numpy as np
ws = np.arange(-100 ,101)
bs = np.arange(-100 ,101)
costs = np.zeros([201 ,201])
i = 0
for w in ws:
  j = 0
  for b in bs:
    cost = compute_cost(x, y ,w ,b)
    costs[i,j] = cost
    j = j+1
  i = i+1

costs

!pip install wget
import wget
wget.download("https://github.com/GrandmaCan/ML/raw/main/Resgression/ChineseFont.ttf")

import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.font_manager import fontManager
fontManager.addfont("ChineseFont.ttf")
mpl.rc('font', family="ChineseFont")

ax = plt.axes(projection="3d")
ax.view_init(45 ,-120) #上下選轉角度 左右旋轉角度
ax.xaxis.set_pane_color((0,0,0))
ax.yaxis.set_pane_color((0,0,0))
ax.zaxis.set_pane_color((0,0,0))
b_grid ,w_grid = np.meshgrid(bs ,ws)
ax.plot_surface(w_grid ,b_grid ,costs ,cmap="Spectral_r" ,alpha = 0.7) #cmap調整匯出的曲線的顏色,alpha使圖面變為透明

ax.set_title("w b 對應的 cost")
ax.set_xlabel("w")
ax.set_ylabel("b")
ax.set_zlabel("cost")

plt.show()